### ISSUE TITLE
Not able to set target

### ISSUE THREAD

**Issue by jednl** [HommiePeter/homebridge-toon-platform#10]
Hi, 

I'm not able to set the target temp on the toon with the latest version of the plugin.
With the same config it works if i rollback to the previous version. However with that version homebridge crashes after every few minutes with this error;

[3/3/2022, 8:50:11 PM] [homebridge-toon-platform] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/3/2022, 8:50:11 PM] [Toon] Current Target Temperature:  undefined
[3/3/2022, 8:50:11 PM] [homebridge-toon-platform] This plugin generated a warning from the characteristic 'Target Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
s
[3/3/2022, 8:50:30 PM] FetchError: invalid json response body at https://api.toon.eu/toon/v3/276275/status reason: Unexpected token < in JSON at position 0
    at /homebridge/node_modules/homebridge-toon-platform/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ToonConnection.getToonStatus (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:144:34)
    at ToonConnection.initialize (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:36:9)
[3/3/2022, 8:50:30 PM] Got SIGTERM, shutting down Homebridge...

Any thoughts?

**Comment by jednl** [comment]
new error, homebridge in a loop:

[3/3/2022, 9:04:54 PM] FetchError: invalid json response body at https://api.toon.eu/toon/v3/276275/status reason: Unexpected token < in JSON at position 0
    at /homebridge/node_modules/homebridge-toon-platform/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ToonConnection.getToonStatus (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:144:34)
    at ToonConnection.initialize (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:36:9)
[3/3/2022, 9:04:54 PM] Got SIGTERM, shutting down Homebridge...

**Comment by jednl** [comment]
Reinstalled the new version, same error. And changing the target temperature on homebridge gui or in homekit does not change the target on Toon.

**Comment by HommiePeter** [comment]
Hello Jednl, 

i see that the new release triggers a issue when loading the Toon Thermostat from the accessory cache. I will look into a solution. A work around would be the clear the accessory cache. As long as it does not reload the accessories from cache it works. But clearing the cache could lead to the situation that in Homekit (Home App) your devices are changed back to their initial location (in the case that you changed the location of your Toon Devices in the Home App afterwards) .

Kind regards, 

Peter

**Comment by ruudbol** [comment]
Same problem, version 0.9.6 is working fine.

kind regards,
Ruud

**Comment by dclaproth** [comment]
> Hello Jednl,
> 
> i see that the new release triggers a issue when loading the Toon Thermostat from the accessory cache. I will look into a solution. A work around would be the clear the accessory cache. As long as it does not reload the accessories from cache it works. But clearing the cache could lead to the situation that in Homekit (Home App) your devices are changed back to their initial location (in the case that you changed the location of your Toon Devices in the Home App afterwards) .
> 
> Kind regards,
> 
> Peter

Any update on this? Got the same problem. Removing Toon from cached accesories (from Homebridge web ui you can remove single accesorie from cache). But if HB restarts problem is back...

**Comment by MikeFumbler** [comment]
Same issue here. 
It runs fine for a week and I am able to control Toon from Hoobs. 

After this the accessory is known to HomeKit, but I cannot control it. 

No errors in the log, also no parameter changes. 

Removing the accessory from HomeKit and reinstalling helps, but only for a week or so. 

Any change for an update?

Thanks!

**Comment by MikeFumbler** [comment]
Sames issues. It does not work anymore.
Many reinstalls, reconnects to HomeBridge, reboots, new API TOKEN, nothing helps.

But after selecting a temperature in Eve or HomeKit:
WARNING:
Errors:
unhandled rejection: FetchError: invalid json response body at...
TypeError: Cannot read properties of undefined...
And so on.

It logs into the API successfully. "Connection was setup". "Bridge is running".

Sometimes the Errors in the Eve (HomeKit) app disappear, and I can set a temperature.
But Toon, nor the Toon app will not react.

Are you still around, Peter? Do you still use Eneco Toon? Or can we consider this abandonware?

**Comment by HommiePeter** [comment]
Hi there all, with the winter times coming I will be pickup up this development beginning of November. 

Greetings

Peter

**Comment by MikeFumbler** [comment]
That is great news, Peter! Thanks.

**Comment by MikeFumbler** [comment]
As soon as you are 'online/on the block' again, I will post my Hoobs log files and my own notes. If that helps.

**Comment by ruudbol** [comment]
Hi Peter, great to hear you will try to solve this issue, any update already .
