### ISSUE TITLE
Error when starting plugin

### ISSUE THREAD

**Issue by MrSnoebel** [HommiePeter/homebridge-toon-platform#2]
(node:17425) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'
Require stack:
- /homebridge/node_modules/homebridge-toon-platform/dist/ToonConnection.js
- /homebridge/node_modules/homebridge-toon-platform/dist/ToonObject.js
- /homebridge/node_modules/homebridge-toon-platform/dist/ToonPlatform.js
- /homebridge/node_modules/homebridge-toon-platform/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at ToonConnection.toonGETRequest (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:96:21)
    at ToonConnection.getAgreementData (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:113:52)
    at ToonConnection.initialize (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:34:37)
    at new ToonConnection (/homebridge/node_modules/homebridge-toon-platform/src/ToonConnection.ts:29:14)
    at new ToonAPI (/homebridge/node_modules/homebridge-toon-platform/src/ToonObject.ts:24:27)
    at new ToonHomebridgePlatform (/homebridge/node_modules/homebridge-toon-platform/src/ToonPlatform.ts:66:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
(Use `node --trace-warnings ...` to show where the warning was created)

Fresh install of the plugin, I am migrating form the old 'jochem725' to this new version.
Homebridge is 1.3.4, running in a docker enviroment.
Node.js version v14.17.1
Npm version v6.14.13

Config:
{
    "platform": "Toon-Platform",
    "apiToken": "<<Correct key filled in>>",
    "switch_smoke": true,
    "switch_hue": false,
    "switch_wallplug": true,
    "agreementIndex": "0",
    "name": "Toon"
}

**Comment by jednl** [comment]
I've got the same issue, also in a docker enviroment.

Any suggestions?

Jacques

**Comment by unequalsine** [comment]
Same issue.

**Comment by lensen** [comment]
`npm install node-fetch@2.6.6` resolved it for me.

**Comment by jednl** [comment]
Thanks! That worked.

**Comment by gielk** [comment]
I have installed this, but this is not resolving the problem for me.

I'm still getting the next error.

[29/12/2021, 18:32:03] Error: Cannot find module 'node-fetch'
Require stack:
- /usr/local/lib/node_modules/homebridge-toon-platform/dist/ToonConnection.js
- /usr/local/lib/node_modules/homebridge-toon-platform/dist/ToonObject.js
- /usr/local/lib/node_modules/homebridge-toon-platform/dist/ToonPlatform.js
- /usr/local/lib/node_modules/homebridge-toon-platform/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ToonConnection.toonGETRequest (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonConnection.ts:96:21)
    at ToonConnection.getAgreementData (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonConnection.ts:113:52)
    at ToonConnection.initialize (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonConnection.ts:34:37)
    at new ToonConnection (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonConnection.ts:29:14)
    at new ToonAPI (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonObject.ts:24:27)
    at new ToonHomebridgePlatform (/usr/local/lib/node_modules/homebridge-toon-platform/src/ToonPlatform.ts:66:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)

**Comment by jednl** [comment]
Do you use a docker enviromemt? I installed it with the terminal in homebridge-ui.

**Comment by gielk** [comment]
> Do you use a docker enviromemt? I installed it with the terminal in homebridge-ui.

I don’t use a docket environment. I also installed it using homebridge-ui.

**Comment by jednl** [comment]
Then we have to wait for an answer from @HommiePeter.

**Comment by gielk** [comment]
`sudo npm install -g node-fetch@2.6.6`

fixed the problem for me.

**Comment by HommiePeter** [comment]
Guy's I released a new version (release 0.9.6) today, which will install the node-fetch as a dependency during installation of the new version of the plugin so that the workaround of doing a sudo npm install -g node-fetch@2.6.6 in the package folder (/usr/lib/node_modules/homebridge-toon-platform) is no longer needed.
